# First we need to configure the deployment for the frontend server
# This is the deployment that will be used to deploy the frontend server to the cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment # This is the label of the deployment
spec:
  selector:
    matchLabels:
      app: frontend # This is the label of the deployment where the pod will be deployed
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend # This is the label of the pod that will be created
    spec:
      containers:
        - name: frontend-container
          image: redaroshdy/frontendimage:latest
          env:
            - name: PORT
              value: "4200"
          ports:
            - containerPort: 8080
---
# Now we need to configure the service for the frontend server
# This is the service that will be used to expose the frontend server to the outside world
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080 # This is the port that the service will listen on inside the cluster
      targetPort: 8080 # This is the port that the service will be exposed on outside the cluster
  type: NodePort
